Feature/rnp 96
onewelcome/sdk-react-native pull request #100
Opened 2022-11-21 11:21 UTC by MichielVrins

2022-11-21 16:15 UTC, aleknow requested changes

2022-11-21 16:15 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/module/RNOneginiSdkModule.kt
> +  fun provideReactApplicationContext() = reactApplicationContext
I think we don't need reactNativeApplication context to be injected anywhere

2022-11-21 16:15 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/OneginiSDK.kt
> +    private val reactApplicationContext: ReactApplicationContext,
application context can be injected directly here:
`private val applicationContext: Context`

2022-11-21 16:15 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/network/AnonymousService.kt
> +    private val applicationDetailsRetrofitClient: ResourcesClient by lazy {
correct retrofit client can also be injected. You can create new dagger module that will have provider methods and each can provide different retrofit client. Each provider would return the same type, thus you will need to use @Named annotation, so dagger knows which one to inject

2022-11-28 14:37 UTC, aleknow requested changes

2022-11-28 14:37 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/network/UserService.kt
> +class UserService  @Inject constructor(@Named(Constants.USER_SERVICE) private val userRetrofitClient: Lazy<ResourcesClient>){
one too many space `UserService  @Inject`

2022-11-28 14:37 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/network/UserService.kt
> +class UserService  @Inject constructor(@Named(Constants.USER_SERVICE) private val userRetrofitClient: Lazy<ResourcesClient>){
You can add import for Constants so there only `@Named(USER_SERVICE)`

2022-11-28 14:37 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/network/ImplicitUserService.kt
> +class ImplicitUserService @Inject constructor(@Named(Constants.IMPLICIT_USER_SERVICE) private val implicitRetrofitClient: Lazy<ResourcesClient>){
You can add import for Constants so there only `@Named(IMPLICIT_USER_SERVICE)`

2022-11-28 14:37 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/network/AnonymousService.kt
> +class AnonymousService @Inject constructor(@Named(Constants.ANONYMOUS_SERVICE) private val anonymousRetrofitClient: Lazy<ResourcesClient>) {
You can add import for Constants so there only `@Named(ANONYMOUS_SERVICE)`

2022-11-28 14:40 UTC, MichielVrins commented on android/src/test/java/com/onegini/mobile/sdk/reactnative/OneginiSdkWrapperTests.kt
> -class OneginiSdkWrapperTests {
We will be removing the SdkWrapper.kt anyway when we move everything into useCases as we can link them up in the RNOneginiSdk class. For now these tests don't actually add any value and are just a nuisance when moving methods into useCases.

2022-11-28 14:49 UTC, aleknow approved these changes

2022-11-28 14:49 UTC, merged