Feature/rnp 124
onewelcome/sdk-react-native pull request #128
Opened 2023-01-11 09:05 UTC by MichielVrins

2023-01-12 16:13 UTC, aleknow requested changes

2023-01-13 10:27 UTC, MichielVrins commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/RNOneginiSdk.kt
>  import javax.inject.Inject
I don't see any unused imports, could you check again? Could it be that you have your IDE set up to recognize multiple imports and merge those together with .*?

2023-01-13 11:40 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/RNOneginiSdk.kt
>  import javax.inject.Inject
According to AS there is `Unresolved reference: IdOneginiAuthenticator`, I see it should be `AuthenticatorId`.
Also AS says that those imports are unused
```
import com.onegini.mobile.sdk.android.handlers.OneginiDeviceAuthenticationHandler
import com.onegini.mobile.sdk.android.handlers.error.OneginiDeviceAuthenticationError
import com.onegini.mobile.sdk.reactnative.mapers.ScopesMapper
```

2023-01-13 13:50 UTC, aleknow approved these changes

2023-01-13 14:18 UTC, merged