Android: Simplify Custom registration
onewelcome/sdk-react-native pull request #149
Opened 2023-02-08 11:24 UTC by MichielVrins

2023-02-08 12:05 UTC, Archifer approved these changes

2023-02-09 14:10 UTC, aleknow requested changes

2023-02-09 14:59 UTC, MichielVrins commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/RegistrationManager.kt
> +class RegistrationManager @Inject constructor(private val oneginiSDK: OneginiSDK) {
That seems entirely reasonsable and I have updated that.

2023-02-09 15:05 UTC, MichielVrins commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/exception/OneginiReactNativeException.kt
> +}
https://onewelcome.atlassian.net/browse/RNP-155

2023-02-09 15:13 UTC, MichielVrins commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/RegistrationManager.kt
> +class RegistrationManager @Inject constructor(private val oneginiSDK: OneginiSDK) {
I did name it CustomRegistrationActionManager as this seems more descriptive

2023-02-09 16:20 UTC, aleknow requested changes

2023-02-09 16:20 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/CustomRegistrationActionManager.kt
> +        customRegistrationActions.add((action))
duplicated `()`

2023-02-09 16:20 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/CustomRegistrationActionManager.kt
> +        return null
you could simplify it to something like this:
`return customRegistrationActions.firstOrNull { it.id == id }`

2023-02-09 16:20 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/CustomRegistrationActionManager.kt
> +        return null
this one could also be simplified:
`customRegistrationActions.firstOrNull { it.isInProgress() }`

2023-02-13 09:38 UTC, aleknow approved these changes

2023-02-13 09:51 UTC, merged