Rnp 72
onewelcome/sdk-react-native pull request #41
Opened 2022-06-01 11:37 UTC by robertszuba

2022-06-10 11:55 UTC, aleknow requested changes

2022-06-10 11:55 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/AuthenticatorManager.kt
>  import com.onegini.mobile.sdk.reactnative.exception.EmptyOneginiErrorDetails
Unused imports

2022-06-10 11:55 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/AuthenticatorManager.kt
> +                    callback.onError(error?.errorType.toString(), error?.message)
Unnecessary safe call on `error` object

2022-06-10 11:55 UTC, aleknow commented on android/src/main/java/com/onegini/mobile/sdk/reactnative/managers/AuthenticatorManager.kt
> +                    callback.onError(error?.errorType.toString(), error?.message)
Unnecessary safe call on `error` object

2022-06-13 11:19 UTC, robertszuba commented
All imports should be fixed now

2022-06-14 07:00 UTC, aleknow approved these changes

2022-06-14 07:00 UTC, merged